seed_everything: 37
trainer:

  default_root_dir: ./results/training_free_uae

  accelerator: cuda
  devices: 1

  log_every_n_steps: 1

  callbacks:
  - class_path: pytorch_lightning.callbacks.RichProgressBar

data: # data.session.text_module.SessionTextDataModule
  batch_size: 64
  sessions_file:
    - ./dataset/phase2/sessions_test_task1.csv
    - ./dataset/phase2/gt_task1.csv
  products_file: ./dataset/products_train.csv

model: # training_free.module.TrainingFreeModule
  model:
    class_path: llm.angle_emb.LLM
    init_args:
      model_name: WhereIsAI/UAE-Large-V1
      pooling_type: cls
      prompt: 'A user has interacted with the following products
        in a session. Represent your prediction of the next product
        in the session they will interact with: {text}'

  vector_io:
    class_path: data.product.io.parquet.ParquetVectorIO
    init_args:
      directory: ./dataset/product_embedding_parquet/uae

  mrr_similarity_batch_size: 20000
